image: node:current-alpine

stages:
  - deploy
 
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

deploy:
  stage: deploy
  script:
    - yarn install
    - yarn lint:full
    - yarn tsc
    - yarn export
    - apk add lftp
    - lftp -e "open $FTP_HOST:$FTP_PORT; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete out/ sistem-informasi/; bye"
