[[headers]]
  for = "/*"
  [headers.values]
    X-DNS-Prefetch-Control = 'on'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'SAMEORIGIN'
    X-XSS-Protection = '1; mode=block'
    Strict-Transport-Security = 'max-age=31536000; includeSubDomains; preload'
    Content-Security-Policy = "default-src 'self';  script-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.com *.googletagmanager.com analytics.google.com; img-src 'self' blob: data: https:; style-src 'self' 'unsafe-inline'; connect-src 'self' www.google-analytics.com analytics.google.com stats.g.doubleclick.net; object-src 'none'; frame-src https://calendar.google.com https://docs.google.com;"
    Referrer-Policy = 'strict-origin-when-cross-origin'
    Permissions-Policy = 'camera=(), microphone=(), geolocation=(), interest-cohort=()'

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
